export const organizationLang = {
    en: {
        title: "Organization",
        createOrganization: "Create Organization",
        members: "Members",
        newOrganization: "New Organization",
        disabled: "Disabled",
        settings: "Settings",
        newProject: "New Project",
        goToProject: "Go to Project",
        search: "Search",
        clear: "Clear",
        deleteMember: "Delete Member",
        deleteMemberConfirm: "Are you sure you want to delete this member?",
        deleteMemberSuccess: "Member deleted successfully",
        deleteMemberFailed: "Failed to delete member",
        deleting: "Deleting...",
        delete: "Delete",
        cancel: "Cancel",
        setAdmin: "Set Admin",
        setAdminConfirm: "Are you sure you want to set this member as admin?",
        setAdminSuccess: "Member set as admin successfully",
        setAdminFailed: "Failed to set member as admin",
        unsetAdmin: "Unset Admin",
        unsetAdminConfirm: "Are you sure you want to unset this member as admin?",
        unsetAdminSuccess: "Member unset as admin successfully",
        unsetAdminFailed: "Failed to unset member as admin",
        setting: "Setting...",
        unsetting: "Unsetting...",
        id: "ID",
        name: "Name",
        email: "Email",
        role: "Role",
        action: "Action",
        allMembers: "All Members",
        inviteMember: "Invite Member",
        inviteMemberConfirm: "Are you sure you want to invite this member?",
        inviteMemberSuccess: "Member invited successfully",
        inviteMemberFailed: "Failed to invite member",
        inviteMemberLoading: "Inviting member...",
        superAdmin: "Super Admin",
        admin: "Admin",
        member: "Member",
        all: "All",
        description: "Description",
        next: "Next",
        create: "Create",
        projectNameMustBeAtLeast3Characters: "Project name and description must be at least 3 characters",
        organizationNameMustBeAtLeast3Characters: "Organization name and description must be at least 3 characters",
        createOrganizationSuccess: "Organization created successfully",
        createOrganizationFailed: "Failed to create organization",
    },
    zh: {
        title: "组织",
        createOrganization: "创建组织",
        members: "成员",
        newOrganization: "新建组织",
        disabled: "已禁用",
        settings: "设置",
        newProject: "新建项目",
        goToProject: "前往项目",
        search: "搜索",
        clear: "清空",
        deleteMember: "删除成员",
        deleteMemberConfirm: "确定要删除该成员吗？",
        deleteMemberSuccess: "成员删除成功",
        deleteMemberFailed: "删除成员失败",
        deleting: "删除中...",
        delete: "删除",
        cancel: "取消",
        setAdmin: "设置管理员",
        setAdminConfirm: "确定要设置该成员为管理员吗？",
        setAdminSuccess: "成员设置为管理员成功",
        setAdminFailed: "设置成员为管理员失败",
        unsetAdmin: "撤销管理员权限",
        unsetAdminConfirm: "确定要撤销该成员的管理员权限吗？",
        unsetAdminSuccess: "撤销管理员权限成功",
        unsetAdminFailed: "撤销管理员权限失败",
        setting: "设置中...",
        unsetting: "撤销中...",
        allMembers: "所有成员",
        id: "ID",
        name: "名称",
        email: "邮箱",
        role: "权限",
        action: "操作",
        all: "全部",
        superAdmin: "超级管理员",
        admin: "管理员",
        member: "成员",
        description: "描述",
        next: "下一步",
        create: "创建",
        createOrganizationSuccess: "组织创建成功",
        createOrganizationFailed: "组织创建失败",
        organizationNameMustBeAtLeast3Characters: "组织名称与组织描述至少3个字符",
        projectNameMustBeAtLeast3Characters: "项目名称与项目描述至少3个字符",
    },
}