export const projectLang = {
    en: {
        settings: "Settings",
        apiKey: "API Key",
        organization: "Organization",
        organizations: "Organizations",
        project: "Project",
        createApiKey: "Create API Key",
        apiKeyName: "API Key Name",
        create: "Create",
        creating: "Creating...",
        cancel: "Cancel",
        createApiKeySuccess: "Create API Key Success",
        createApiKeyFailed: "Create API Key Failed",
        deleteApiKey: "Delete API Key",
        deleteApiKeyConfirmation: "Are you sure you want to delete this API key?",
        deleteApiKeySuccess: "Delete API Key Success",
        deleteApiKeyFailed: "Delete API Key Failed",
        delete: "Delete",
        deleting: "Deleting...",
        updateApiKey: "Update API Key",
        updateApiKeySuccess: "Update API Key Success",
        updateApiKeyFailed: "Update API Key Failed",
        updating: "Updating...",
        update: "Update",
        disableApiKey: "Disable API Key",
        disableApiKeyConfirmation: "Are you sure you want to disable this API key?",
        disableApiKeySuccess: "Disable API Key Success",
        disableApiKeyFailed: "Disable API Key Failed",
        disabling: "Disabling...",
        disable: "Disable",
        enableApiKey: "Enable API Key",
        enableApiKeyConfirmation: "Are you sure you want to enable this API key?",
        enableApiKeySuccess: "Enable API Key Success",
        enableApiKeyFailed: "Enable API Key Failed",
        enabling: "Enabling...",
        enable: "Enable",
        getApiKeyListFailed: "Failed to get api key list",
        allApiKeys: "All API Keys",
        name: "Name",
        key: "Key",
        status: "Status",
        action: "Action",
        deleteProject: "Delete Project",
        deleteProjectConfirmation: "Are you sure you want to delete this project?",
        deleteProjectSuccess: "Delete Project Success",
        deleteProjectFailed: "Delete Project Failed",
        saving: "Saving...",
        save: "Save",
        editProject: "Edit Project",
        editProjectSuccess: "Edit Project Success",
        editProjectFailed: "Edit Project Failed",
        active: "Active",
        disabled: "Disabled",
        description: "Description",
        projectSettings: "Project Settings",
        projectName: "Project Name",
        projectDescription: "Project Description",
        projectStatus: "Project Status",
        edit: "Edit",
        noDescription: "No Description",
    },
    zh: {
        settings: "设置",
        apiKey: "API Key",
        organization: "组织",
        organizations: "组织",
        project: "项目",
        createApiKey: "创建 API Key",
        apiKeyName: "名称",
        create: "创建",
        creating: "创建中...",
        cancel: "取消",
        createApiKeySuccess: "创建 API Key 成功",
        createApiKeyFailed: "创建 API Key 失败",
        deleteApiKey: "删除 API Key",
        deleteApiKeyConfirmation: "确定要删除这个 API Key 吗？",
        deleteApiKeySuccess: "删除 API Key 成功",
        deleteApiKeyFailed: "删除 API Key 失败",
        deleting: "删除中...",
        delete: "删除",
        updateApiKey: "更新 API Key",
        updateApiKeySuccess: "更新 API Key 成功",
        updateApiKeyFailed: "更新 API Key 失败",
        updating: "更新中...",
        update: "更新",
        disableApiKey: "禁用 API Key",
        disableApiKeyConfirmation: "确定要禁用这个 API Key 吗？",
        disableApiKeySuccess: "禁用 API Key 成功",
        disableApiKeyFailed: "禁用 API Key 失败",
        disabling: "禁用中...",
        disable: "禁用",
        enableApiKey: "启用 API Key",
        enableApiKeyConfirmation: "确定要启用这个 API Key 吗？",
        enableApiKeySuccess: "启用 API Key 成功",
        enableApiKeyFailed: "启用 API Key 失败",
        enabling: "启用中...",
        enable: "启用",
        getApiKeyListFailed: "获取 API Key 列表失败",
        allApiKeys: "All API Keys",
        name: "名称",
        key: "Key",
        status: "状态",
        action: "操作",
        deleteProject: "删除项目",
        deleteProjectConfirmation: "确定要删除这个项目吗？",
        deleteProjectSuccess: "删除项目成功",
        deleteProjectFailed: "删除项目失败",
        description: "描述",
        projectSettings: "项目设置",
        projectName: "项目名称",
        projectDescription: "项目描述",
        projectStatus: "项目状态",
        editProject: "编辑项目",
        editProjectSuccess: "编辑项目成功",
        editProjectFailed: "编辑项目失败",
        saving: "保存中...",
        save: "保存",
        active: "启用",
        disabled: "禁用",
        edit: "编辑",
        noDescription: "无描述",
    },
}