export const organizationLang = {
    en: {
        organization: "Organization",
        organizations: "Organizations",
        projects: "Projects",
        settings: "Settings",
        organizationNotFound: "Organization not found",
        failedToFetchOrganizationData: "Failed to fetch organization data",
        failedToFetchOrganizationMemberInfo: "Failed to fetch organization member info",
        newProject: "New Project",
        organizationSettings: "Organization Settings",
        members: "Members",
        deleteOrganization: "Delete Organization",
        deleting: "Deleting...",
        delete: "Delete",
        cancel: "Cancel",
        deleteOrganizationSuccess: "Delete organization success",
        deleteOrganizationFailed: "Delete organization failed",
        deleteOrganizationConfirmation: "Are you sure you want to delete this organization?",
        quitOrganization: "Quit Organization",
        quitting: "Quitting...",
        quit: "Quit",
        quitOrganizationConfirmation: "Are you sure you want to quit this organization?",
        quitOrganizationSuccess: "Quit organization success",
        quitOrganizationFailed: "Quit organization failed",
        save: "Save",
        saving: "Saving...",
        status: "Status",
        active: "Active",
        disabled: "Disabled",
        editOrganization: "Edit Organization",
        editOrganizationSuccess: "Edit organization success",
        editOrganizationFailed: "Edit organization failed",
        name: "Name",
        description: "Description",
        fetchOrganizationInfoFailed: "Failed to fetch organization info",
        edit: "Edit",
        switchLabel: "Switch label",
        deleteMember: "Delete Member",
        deleteMemberConfirmation: "Are you sure you want to delete this member?",
        deleteMemberSuccess: "Delete member success",
        deleteMemberFailed: "Delete member failed",
        setOrganizationAdmin: "Set Organization Admin",
        setOrganizationAdminConfirmation: "Are you sure you want to set this member as the organization admin?",
        setOrganizationAdminSuccess: "Set organization admin success",
        setOrganizationAdminFailed: "Set organization admin failed",
        setting: "Setting...",
        setAdmin: "Set Admin",
        unsetOrganizationAdmin: "Unset Organization Admin",
        unsetAdmin: "Unset Admin",
        unsetAdminConfirmation: "Are you sure you want to unset this member as the organization admin?",
        unsetAdminSuccess: "Unset organization admin success",
        unsetAdminFailed: "Unset organization admin failed",
        unsetting: "Unsetting...",
        addMember: "Add Member",
        search: "Search",
        searching: "Searching...",
        adding: "Adding...",
        searchUserFailed: "Search user failed",
        addMemberSuccess: "Add member success",
        addMemberFailed: "Add member failed",
        addMemberConfirmation: "Search user by email to add member",
        addMemberConfirmationSuccess: "Add member success",
        addMemberConfirmationFailed: "Add member failed",
        email: "Email",
        username: "Username",
        user_id: "User ID",
        enterEmail: "Enter email",
        inviteMember: "Invite Member",
        inviteMemberByLink: "Invite members by Link:(click to copy)",
        copiedSuccess: "Copied success",
        getInviteLinkFailed: "Get invite link failed",
        allMembers: "All Members",
        id: "ID",
        role: "Role",
        action: "Action",
        goToProject: "Go to Project",
    },
    zh: {
        organization: "组织",
        organizations: "组织",
        projects: "项目",
        settings: "设置",
        organizationNotFound: "组织不存在",
        failedToFetchOrganizationData: "获取组织数据失败",
        failedToFetchOrganizationMemberInfo: "获取组织成员信息失败",
        newProject: "新建项目",
        organizationSettings: "组织设置",
        members: "成员",
        deleteOrganization: "删除组织",
        deleting: "删除中...",
        delete: "删除",
        cancel: "取消",
        deleteOrganizationSuccess: "删除组织成功",
        deleteOrganizationFailed: "删除组织失败",
        deleteOrganizationConfirmation: "确定要删除这个组织吗？",
        quitOrganization: "退出组织",
        quitting: "退出中...",
        quit: "退出",
        quitOrganizationConfirmation: "确定要退出这个组织吗？",
        quitOrganizationSuccess: "退出组织成功",
        quitOrganizationFailed: "退出组织失败",
        active: "启用",
        disabled: "禁用",
        editOrganization: "编辑组织",
        editOrganizationSuccess: "编辑组织成功",
        editOrganizationFailed: "编辑组织失败",
        status: "状态",
        name: "名称",
        description: "描述",
        save: "保存",
        saving: "保存中...",
        fetchOrganizationInfoFailed: "获取组织信息失败",
        edit: "编辑",
        switchLabel: "开关标签",
        deleteMember: "删除成员",
        deleteMemberConfirmation: "确定要删除这个成员吗？",
        deleteMemberSuccess: "删除成员成功",
        deleteMemberFailed: "删除成员失败",
        setOrganizationAdmin: "设置组织管理员",
        setOrganizationAdminConfirmation: "确定要设置这个成员为组织管理员吗？",
        setOrganizationAdminSuccess: "设置组织管理员成功",
        setOrganizationAdminFailed: "设置组织管理员失败",
        setting: "设置中...",
        setAdmin: "确认",
        unsetOrganizationAdmin: "取消组织管理员",
        unsetAdmin: "确认",
        unsetAdminConfirmation: "确定要取消这个成员的组织管理员权限吗？",
        unsetAdminSuccess: "取消组织管理员权限成功",
        unsetAdminFailed: "取消组织管理员权限失败",
        unsetting: "取消中...",
        email: "邮箱",
        username: "用户名",
        user_id: "用户ID",
        enterEmail: "输入邮箱",
        addMember: "添加成员",
        search: "搜索",
        searching: "搜索中...",
        searchUserFailed: "搜索用户失败",
        addMemberConfirmation: "通过邮箱搜索用户并添加成员",
        addMemberSuccess: "添加成员成功",
        addMemberFailed: "添加成员失败",
        adding: "添加中...",
        inviteMember: "邀请成员",
        inviteMemberByLink: "通过链接邀请成员:(点击复制)",
        copiedSuccess: "复制成功",
        getInviteLinkFailed: "获取邀请链接失败",
        allMembers: "所有成员",
        role: "角色",
        action: "操作",
        id: "ID",
        goToProject: "前往项目",
    },
}