export const knowledgeBaseLang = {
    en: {
        knowledgeBase: "Knowledge Base",
        files: "files",
        delete: "Delete",
        settings: "Settings",
        fetchFailed: "Fetch knowledge bases failed",
        noDescription: "No Description",
        search: "Search",
        newKnowledgeBase: "New Knowledge Base",
        noKnowledgeBases: "No Knowledge Bases",
        createKnowledgeBase: "Create Knowledge Base",
        addKnowledgeBaseEntry: "Add Knowledge Base Entry",
        name: "Name",
        description: "Description",
        pleaseFillInAllFields: "Please fill in all fields.",
        addKnowledgeBaseEntrySuccess: "Add knowledge base entry success",
        addKnowledgeBaseEntryFailed: "Add knowledge base entry failed",
        creating: "Creating",
        create: "Create",
        cancel: "Cancel",
        deleteKnowledgeBaseEntrySuccess: "Delete knowledge base entry success",
        deleteKnowledgeBaseEntryFailed: "Delete knowledge base entry failed",
        deleteKnowledgeBase: "Delete Knowledge Base",
        areYouSureYouWantToDelete: "Are you sure you want to delete",
        thisKnowledgeBase: "this knowledge base",
        deleting: "Deleting",
        updating: "Updating",
        update: "Update",
        updateKnowledgeBaseEntrySuccess: "Update knowledge base entry success",
        updateKnowledgeBaseEntryFailed: "Update knowledge base entry failed",
        updateKnowledgeBase: "Update Knowledge Base",
        documents: "Documents",
        hitTest: "Hit Test",
        failedToFetchKnowledgeBase: "Failed to fetch knowledge base",
        failedToUploadDocument: "Failed to upload document",
        pleaseFillInAllChunkRuleParameters: "Please fill in all chunk rule parameters",
        chunkRuleParameterCannotBeEmpty: "Chunk rule parameter cannot be empty",
        youCanOnlyUpload: "Unsupported file type",
        file: "file",
        fileUploadedSuccessfully: "file uploaded successfully",
        fileUploadFailed: "file upload failed",
        currentlySupport: "Currently support PDF、TXT files, with a maximum size of 10MB per file.",
        chunkRuleSettings: "Chunk Rule Settings",
        separators: "Separators",
        separatorDescription: "The separator is used to split the text into vectors. You can use one or more separators. For example, if you want to use both \"\\n\" and \"\\t\" as separators, you can separate them with commas like this: \"\\n,\\t\".",
        chunkRule: "Chunk Rule",
        chunkRuleDescription: "The chunk rule is used to split the text into vectors. You can use one or more chunk rules. For example, if you want to use both \"\\n\" and \"\\t\" as chunk rules, you can separate them with commas like this: \"\\n,\\t\".",
        clickOrDragFileToThisAreaToUpload: "Click or drag file to this area to upload",
        uploadDocument: "Upload Document",
        maxChunkSize: "Max Chunk Size",
        maxChunkSizeDescription: "The maximum size of a chunk in tokens.",
        pleaseFillInTheSeparator: "Please fill in the separator.",
        pleaseFillInTheMaxChunkSize: "Please fill in the max chunk size.",
        documentUploadedSuccessfully: "Document uploaded successfully", 
        pleaseFillInTheChunkOverlap: "Please fill in the chunk overlap.",
        chunkOverlap: "Chunk Overlap",
        chunkOverlapDescription: "The overlap between chunks in bytes.Suggest to set it to 10%-25% of the max chunk size.",
        nextStep: "Next Step",
        upload: "Upload",
        back: "Back",
        complete: "Complete",
        updateDocument: "Update Document",
        documentTitle: "Document Title",
        updateDocumentFailed: "Update document failed",
        updateDocumentSuccess: "Update document success",
        deleteDocument: "Delete Document",
        deleteDocumentFailed: "Delete document failed",
        deleteDocumentSuccess: "Delete document success",
        noData: "No data",
        id: "ID",
        uploadedAt: "Uploaded-At",
        action: "Action",
        status: "Status",
        size: "Size",
        type: "Type",
        allDocuments: "All Documents",
        addDocument: "Add Document",
        all: "All",
        saving: "Saving",
        save: "Save",
        editChunk: "Edit Chunk",
        editTheContentOfThe: "Edit the content of the",
        chunk: "Chunk",
        fetchDocumentFailed: "Failed to fetch document",
        fetchChunkListFailed: "Failed to fetch chunk list",
        updateChunkFailed: "Failed to update chunk",
        updateChunkSuccess: "Update chunk success",
        pleaseSelectAChunk: "Please select a chunk",
        chunkCount: "Chunk Count",
        chunkSize: "Chunk Size",
        fileName: "File Name",
        fileType: "File Type",
        fileSize: "File Size",
        createdAt: "Create At",
        lastUpdateAt: "Last Update At",
        fileHash: "File Hash",
        allChunks: "All Chunks",
        viewAll: "Expand/Collapse",
        searchChunks: "Search chunks",
        chunkIndex: "Chunk Index",
        tokenCount: "Token Count",
        searchSetting: "Search Setting",
        topKDescription: "The number of results to return.",
        searchTextCannotBeEmpty: "Search text cannot be empty",
        searchFailed: "Failed to search",
        searchResultWillBeDisplayedHere: "Search result will be displayed here",
        totalHits: "Total hits",
        searching: "Searching...",
        searchText: "Search Text",
        knowledgeBaseSetting: "Knowledge Base Setting",
        knowledgeBaseName: "Knowledge Base Name",
        knowledgeBaseDescription: "Knowledge Base Description",
    },
    zh: {
        knowledgeBase: "知识库",
        files: "文件",
        delete: "删除",
        settings: "设置",
        noDescription: "无描述",
        fetchFailed: "获取知识库失败",
        search: "搜索",
        newKnowledgeBase: "新建知识库",
        noKnowledgeBases: "未找到相关知识库",
        createKnowledgeBase: "创建知识库",
        addKnowledgeBaseEntry: "新建知识库条目",
        name: "名称",
        description: "描述",
        pleaseFillInAllFields: "请填写所有字段。",
        addKnowledgeBaseEntrySuccess: "添加知识库条目成功",
        addKnowledgeBaseEntryFailed: "添加知识库条目失败",
        creating: "创建中",
        create: "创建",
        cancel: "取消",
        deleteKnowledgeBaseEntrySuccess: "删除知识库成功",
        deleteKnowledgeBaseEntryFailed: "删除知识库失败",
        deleteKnowledgeBase: "删除知识库",
        areYouSureYouWantToDelete: "确定要删除",
        thisKnowledgeBase: "知识库",
        deleting: "删除中",
        updating: "更新中",
        update: "更新",
        updateKnowledgeBaseEntrySuccess: "更新知识库条目成功",
        updateKnowledgeBaseEntryFailed: "更新知识库条目失败",
        updateKnowledgeBase: "更新知识库",
        documents: "文档",
        hitTest: "召回测试",
        failedToFetchKnowledgeBase: "获取知识库失败",
        failedToUploadDocument: "上传文档失败",
        pleaseFillInAllChunkRuleParameters: "请填写所有规则参数",
        chunkRuleParameterCannotBeEmpty: "规则参数不能为空",
        youCanOnlyUpload: "不支持的文件类型",
        file: "文件",
        fileUploadedSuccessfully: "文件上传成功",
        fileUploadFailed: "文件上传失败",
        currentlySupport: "支持PDF、TXT文件，单个文件最大10MB",
        chunkRuleSettings: "拆分规则设置",
        separators: "分隔符",
        separatorDescription: "分隔符用于将文本拆分为向量。您可以使用一个或多个分隔符。例如，如果您想使用\"\\n\"和\"\\t\"作为分隔符，您可以像这样用逗号分隔它们：\"\\n,\\t\"。",
        chunkRule: "分块规则",
        chunkRuleDescription: "拆分规则用于将文本拆分为向量。您可以使用一个或多个拆分规则。例如，如果您想使用\"\\n\"和\"\\t\"作为拆分规则，您可以像这样用逗号分隔它们：\"\\n,\\t\"。",
        clickOrDragFileToThisAreaToUpload: "点击或拖动文件到此区域上传",
        uploadDocument: "上传文档",
        maxChunkSize: "最大分块大小",
        maxChunkSizeDescription: "分块的最大大小（以tokens为单位）。",
        pleaseFillInTheSeparator: "请填写分隔符。",
        pleaseFillInTheMaxChunkSize: "请填写最大分块大小。",
        documentUploadedSuccessfully: "文档上传成功",
        pleaseFillInTheChunkOverlap: "请填写分块重叠。",
        chunkOverlap: "分块重叠长度",
        chunkOverlapDescription: "分块之间的重叠（以字节为单位）。建议设置为最大分块大小的10%-25%。",
        nextStep: "下一步",
        upload: "上传",
        back: "返回",
        complete: "完成",
        updateDocument: "更新文档",
        documentTitle: "文档标题",
        updateDocumentFailed: "更新文档失败",
        updateDocumentSuccess: "更新文档成功",
        deleteDocument: "删除文档",
        deleteDocumentFailed: "删除文档失败",
        deleteDocumentSuccess: "删除文档成功",
        noData: "暂无数据",
        document: "文档",
        id: "ID",
        uploadedAt: "上传时间",
        action: "操作",
        status: "状态",
        size: "大小",
        type: "类型",
        allDocuments: "所有文档",
        addDocument: "添加文档",
        all: "全部",
        saving: "保存中",
        save: "保存",
        editChunk: "编辑分块",
        editTheContentOfThe: "编辑",
        chunk: "分块",
        fetchDocumentFailed: "获取文档失败",
        fetchChunkListFailed: "获取分块列表失败",
        updateChunkFailed: "更新分块失败",
        updateChunkSuccess: "更新分块成功",
        pleaseSelectAChunk: "请选择一个分块",
        chunkCount: "分块数量",
        chunkSize: "分块大小",
        fileName: "文件名",
        fileType: "文件类型",
        fileSize: "文件大小",
        createdAt: "创建时间",
        lastUpdateAt: "最后更新时间",
        fileHash: "文件哈希",
        allChunks: "所有分块",
        viewAll: "展开/折叠",
        searchChunks: "搜索分块",
        chunkIndex: "分块索引",
        tokenCount: "分块token数量",
        searchSetting: "设置",
        topKDescription: "最大返回结果数量。",
        searchText: "搜索文本",
        searchTextCannotBeEmpty: "搜索文本不能为空",
        searchResultWillBeDisplayedHere: "搜索结果将显示在这里",
        totalHits: "总计命中",
        searching: "搜索中...",
        searchFailed: "搜索失败",
        knowledgeBaseSetting: "知识库设置",
        knowledgeBaseName: "知识库名称",
        knowledgeBaseDescription: "知识库描述",
        saveFailed: "保存失败",
        saveSuccess: "保存成功",
    },
}